# Generated by Django 3.0.7 on 2020-06-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
